### ISSUE TITLE
ValueError：num_samples should be a positive integeral value,but got num_samples =0 

### ISSUE THREAD

**Issue by Freedomxt** [Yu-Wu/One-Example-Person-ReID#1]
Hello,When i train the model ,i will always get this problem?Is anyone have solved it？

Traceback (most recent call last):
  File "run.py", line 123, in <module>
    main(parser.parse_args())
  File "run.py", line 87, in main
    eug.train(new_train_data, unselected_data, step, loss=args.loss, epochs=args.epochs, step_size=args.step_size, init_lr=0.1) if step != resume_step else eug.resume(ckpt_file, step)
  File "/home/xutian/One-Example-Person-ReID-master/reid/eug.py", line 92, in train
    return self.softmax_train(train_data, unselected_data, step, epochs, step_size, init_lr, dropout, loss)
  File "/home/xutian/One-Example-Person-ReID-master/reid/eug.py", line 135, in softmax_train
    u_dataloader = self.get_dataloader(unselected_data, training=True, is_ulabeled=True)
  File "/home/xutian/One-Example-Person-ReID-master/reid/eug.py", line 82, in get_dataloader
    shuffle=training, pin_memory=True, drop_last=training)
  File "/home/xutian/tools/anaconda3/envs/freedom/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "/home/xutian/tools/anaconda3/envs/freedom/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 64, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0

**Comment by Yu-Wu** [comment]
@Freedomxt 

I am not sure about this problem. Did you download the data and unzip it at the correct path (./data/market1501/) ?

**Comment by Freedomxt** [comment]
> @Freedomxt
> 
> I am not sure about this problem. Did you download the data and unzip it at the correct path (./data/market1501/) ?

yes，i have put the data in the right place!  This error appeared in the last step and all of the unlabeled data have been selected!

**Comment by Freedomxt** [comment]
> > @Freedomxt
> > I am not sure about this problem. Did you download the data and unzip it at the correct path (./data/market1501/) ?
> 
> yes，i have put the data in the right place! This error appeared in the last step and all of the unlabeled data have been selected!

I means that the program was operating right  in the first ten training steps and error showed in the last training step.   I guess that all of the unlabeld data have been selected and there is no data to be select  cause this error!

**Comment by Freedomxt** [comment]
> @Freedomxt
> 
> I am not sure about this problem. Did you download the data and unzip it at the correct path (./data/market1501/) ?

I means that the program was operating right in the first ten training steps and error showed in the last training step. I guess that all of the unlabeld data have been selected and there is no data to be select cause this error!

**Comment by Yu-Wu** [comment]
@Freedomxt  
Thanks for your reply. 
You are correct. I will fix it later.

**Comment by mstarZheng** [comment]
The problem I encountered is the same as yours. Is your solution solved?

**Comment by Yu-Wu** [comment]
@mstarZheng 

Please see the commit https://github.com/Yu-Wu/One-Example-Person-ReID/commit/42580ede787b65f2e8a2d2fe9aff264e3be43d04

I have fixed the issue in this commit.
