### ISSUE TITLE
How to get the static strategy work?

### ISSUE THREAD

**Issue by chenyanqi-C** [Yu-Wu/One-Example-Person-ReID#10]
Thanks for your many great works! 
I have a question about how to get the static strategy work,such as  the DGM+IDE ,which rank-1=36.8 and map=16.9 ? 
Many thanks for you !

**Comment by Yu-Wu** [comment]
Please revise their code to use the IDE features.

**Comment by chenyanqi-C** [comment]
Thanks for your reply.I will try it again.
