### ISSUE TITLE
  File "run.py", line 61, in main     l_data, u_data = get_init_shot_in_cam1(dataset_all, load_path="./examples/{}_init_{}.pickle".format(dataset_all.name, args.init), init=args.init) AttributeError: 'Market1501' object has no attribute 'name'

### ISSUE THREAD

**Issue by ly-jy** [Yu-Wu/One-Example-Person-ReID#6]

**Comment by Yu-Wu** [comment]
Please check the content in ``examples''.

**Comment by ly-jy** [comment]
File "run.py", line 61, in main
    l_data, u_data = get_init_shot_in_cam1(dataset_all, load_path="./examples/market1501_init_0.2.pickle".format(dataset_all.name, args.init), init=args.init)
AttributeError: 'Market1501' object has no attribute 'name'

**Comment by Yu-Wu** [comment]
@ly-jy 
Please use original code.

There is attribute 'name' for this object.

https://github.com/Yu-Wu/One-Example-Person-ReID/blob/829fb585a10cb4948a70ee53aeca348b8ed4aa8c/reid/datasets/market1501.py#L12

**Comment by ly-jy** [comment]
When I run "sh run.sh" in the terminal,：
Files already downloaded and verified
Market1501 dataset loaded
  subset   | # ids | # images
  ---------------------------
  train    |   651 |    11329
  val      |   100 |     1607
  trainval |   751 |    12936
  query    |   750 |    16483
  gallery  |   751 |    19281
Traceback (most recent call last):
  File "run.py", line 125, in <module>
    main(parser.parse_args())
  File "run.py", line 61, in main
    l_data, u_data = get_init_shot_in_cam1(dataset_all, load_path="./examples/{}_init_{}.pickle".format(dataset_all.name, args.init), init=args.init)
AttributeError: 'Market1501' object has no attribute 'name'
How can I use the original code you said?

**Comment by ly-jy** [comment]
Excuse me, are you sure the code can run?
Can you run to make sure it can run?
I tried my best and didn't run through it.
Please help me, thank you very much!

**Comment by Yu-Wu** [comment]
@ly-jy 

Please run this code under a clean python environment. 
It seems you might have ``installed'' the reid module of other codes before. Therefore, the module ``Market1501'' might be referred to a previous installed path.

**Comment by ly-jy** [comment]
Thank you for your patience and answer. I hope you can help me. My problems are as follows:

I downloaded the code to the 'home' and upzip it. Put in the data set and run "sh run.sh" in the terminal. Report the error:
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from reid.eug import *
ModuleNotFoundError: No module named 'reid.eug'

I cut out the 'eug.py' and modify ‘ from reid.eug import * ’ to ' ‘from eug import * ', And run 'sh run.sh'.Report the error:
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from eug import *
  File "/home/ly/liyang/One-Example-Person-ReID-master/eug.py", line 17, in <module>
    from reid.exclusive_loss import ExLoss
ModuleNotFoundError: No module named 'reid.exclusive_loss'

I cut out the 'exclusive_loss.py' and modify ‘ from reid.exclusive_loss import ExLoss * ’ to ' from exclusive_loss import ExLoss * ', And run 'sh run.sh'.Report the error:
Files already downloaded and verified
Market1501 dataset loaded
  subset   | # ids | # images
  ---------------------------
  train    |   651 |    11228
  val      |   100 |     1708
  trainval |   751 |    12936
  query    |   750 |    16483
  gallery  |   751 |    19281
Traceback (most recent call last):
  File "run.py", line 125, in <module>
    main(parser.parse_args())
  File "run.py", line 61, in main
    l_data, u_data = get_init_shot_in_cam1(dataset_all, load_path="./examples/{}_init_{}.pickle".format(dataset_all.name, args.init), init=args.init)
AttributeError: 'Market1501' object has no attribute 'name'

I change ' l_data, u_data = get_init_shot_in_cam1(dataset_all, load_path="./examples/{}_init_{}.pickle".format(dataset_all.name, args.init), init=args.init) ' to ' l_data, u_data = get_init_shot_in_cam1(dataset_all, load_path="./examples/market1501_init_0.2.pickle".format(dataset_all.name, args.init), init=args.init) '. But still an error：
  File "run.py", line 61, in main
    l_data, u_data = get_init_shot_in_cam1(dataset_all, load_path="./examples/market1501_init_0.2.pickle".format(dataset_all.name, args.init), init=args.init)
AttributeError: 'Market1501' object has no attribute 'name'

How can I do?

**Comment by Yu-Wu** [comment]
@ly-jy 

You should not fix the issue in this way......

I have updated my code just now. You can try the new code. 
Please make sure you are using python3.

**Comment by ly-jy** [comment]
Thank you very much for your answer. I have used python3, but I have encountered the following problem:
I downloaded the code to the 'home' and upzip it. I run "sh run.sh" in the terminal. Report the error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ly/One-Example-Person-ReID-master/data/market1501/train

I changed the ‘bounding_box_train’ file in the market to ‘train’, 'bounding_box_test' to 'gallery'.Then I put ‘train’, 'gallery', 'query' into the '/home/ly/One-Example-Person-ReID-master/data/market1501' file. And run 'sh run.sh'. Report the error:
NotADirectoryError: [Errno 20] Not a directory: '/home/ly/One-Example-Person-ReID-master/data/market1501/train/0002_c1s1_000451_03.jpg'
File '0002_c1s1_000451_03.jpg' already exists in file 'train', why is it still reported error?

**Comment by ly-jy** [comment]
Thank you very much for your answer. I have used python3, but I have encountered the following problem:
I downloaded the code to the 'home' and upzip it. I run "sh run.sh" in the terminal. Report the error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ly/One-Example-Person-ReID-master/data/market1501/train

I changed the ‘bounding_box_train’ file in the market to ‘train’, 'bounding_box_test' to 'gallery'.Then I put ‘train’, 'gallery', 'query' into the '/home/ly/One-Example-Person-ReID-master/data/market1501' file. And run 'sh run.sh'. Report the error:
NotADirectoryError: [Errno 20] Not a directory: '/home/ly/One-Example-Person-ReID-master/data/market1501/train/0002_c1s1_000451_03.jpg'
File '0002_c1s1_000451_03.jpg' already exists in file 'train'.How can I do?

**Comment by Yu-Wu** [comment]
@ly-jy 
You should use my changed dataset since I changed file names to make sure Image dataset work the same as the video dataset.

Please download them using the provided dataset link in readme.

**Comment by ly-jy** [comment]
Hello author, I have some thoughts after reading your article. I want to know how the datasets you provide are processed. Can you share your code that processes the dataset? I am very grateful! Plase help me! Thank you very much!

**Comment by ly-jy** [comment]
Hello author, I have some thoughts after reading your article. I want to know how the datasets you provide are processed. Can you share your code that processes the dataset? I am very grateful! Plase help me! Thank you very much!

**Comment by ly-jy** [comment]
> @ly-jy
> You should use my changed dataset since I changed file names to make sure Image dataset work the same as the video dataset.
> 
> Please download them using the provided dataset link in readme.

 I want to know how the datasets you provide are changed. Can you share your code that change the dataset? I am very grateful! Plase help me! Thank you very much!

**Comment by Yu-Wu** [comment]
Sorry that the processing code is lost.

For your own dataset, you can use a very simple python scripts to generate the same format as ours. To do this, you only need some basic file operations.

**Comment by Yu-Wu** [comment]
You can see the difference between the original Market dataset and my provided one. It's very simple to generate our format.

You can also see https://github.com/Yu-Wu/DukeMTMC-VideoReID/blob/master/README.md to better understand my "Directory Structure"

**Comment by ly-jy** [comment]
Thank you very much for your answer. If you are convenient, I hope you can provide the code. Thank you so much！Plase help me! Thank you very much!

**Comment by Yu-Wu** [comment]
Sorry that the code is lost.

I cannot find it.
