### ISSUE TITLE
How to use run.sh with Pycharm editor?

### ISSUE THREAD

**Issue by chenyanqi-C** [Yu-Wu/One-Example-Person-ReID#9]
Hello author, I am recreating your paper. I want to ask how to use the Pycharm editor to run the run.sh file. I am a beginner. I want to adjust the parameters in the code because my GPU memory is not enough. What can I do? Thank you very much.

**Comment by Yu-Wu** [comment]
@chenyanqi-C 
Sorry that I haven't try Pycharm before. 

Could you revise `run.sh' in Pycharm and then execute the file in the command line?

**Comment by chenyanqi-C** [comment]
Thanks for your reply, I have try this way,but it does not matter.
 I have another question ,my GPU memory is not enough, which parameters should I adjust.I have try set max_frame smaller, but it seems useless, thank you.

**Comment by Yu-Wu** [comment]
@chenyanqi-C 

What is the exact number of your GPU memory?

**Comment by chenyanqi-C** [comment]
My GPU memory is 6G.

**Comment by Yu-Wu** [comment]
The GPU memory is too small. Did it work well in training?

**Comment by Yu-Wu** [comment]
Or the process corrupts immediately after it begins?

**Comment by chenyanqi-C** [comment]
I ran the run.py program, and he can do it during the training part, but when it comes to "Creat dataloader for Test with batch_size 1", the "out of memory" problem occurs

**Comment by Yu-Wu** [comment]
Which dataset? MARS?

For MARS, you might set the max_frames to 300 or less.

**Comment by chenyanqi-C** [comment]
I use mars.Should I set the batch_size , step_size,etc ,parameters?
And because I don't use run.sh to run, then in which .py file should I modify the max_frame value?

**Comment by Yu-Wu** [comment]
@chenyanqi-C 
You can directly input the command, as it in the file ``run.sh''.

**Comment by chenyanqi-C** [comment]
Is the command entered in the run.sh file? What command should I enter and how to run it.Can you tell me the specific operation? Thank you very much

**Comment by Yu-Wu** [comment]
https://github.com/Yu-Wu/One-Example-Person-ReID/blob/f792dde4330b9e7c42e2239ebe68afd1df05252d/run.sh#L20

Please see this line. 
Use this command, and replace $xx by the expected value.

**Comment by chenyanqi-C** [comment]
ok,I will try it again.thanks for your answer.

**Comment by chenyanqi-C** [comment]
Hello, I have a new question. Among the parameters, what is the use of max_frames, I have looked for a long time, but did not understand. Thank you very much.
